openapi: 3.1.0
info:
  title: Bybit Universal Kline API
  version: 1.0.0
  description: |
    This is the OpenAPI definition for Bybit's Kline (candlestick) data endpoint.
    It allows users to fetch OHLCV data for any symbol and interval.
servers:
  - url: https://api.bybit.com

paths:
  /v5/market/kline:
    get:
      summary: Get candlestick data for any Bybit symbol
      operationId: getKlineData
      parameters:
        - name: category
          in: query
          required: true
          description: Product type
          schema:
            type: string
            enum: [linear, inverse, spot]
            example: linear

        - name: symbol
          in: query
          required: true
          description: Trading pair symbol (e.g. BTCUSDT)
          schema:
            type: string
            example: BTCUSDT

        - name: interval
          in: query
          required: true
          description: Timeframe for each candlestick
          schema:
            type: string
            enum: ["1", "3", "5", "15", "30", "60", "120", "240", "360", "720", "D", "W", "M"]
            example: "15"

        - name: limit
          in: query
          required: false
          description: Number of candles to return (default 200)
          schema:
            type: integer
            default: 200

        - name: start
          in: query
          required: false
          description: Start timestamp (ms)
          schema:
            type: integer

        - name: end
          in: query
          required: false
          description: End timestamp (ms)
          schema:
            type: integer

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  retCode:
                    type: integer
                  retMsg:
                    type: string
                  result:
                    type: object
                    properties:
                      list:
                        type: array
                        items:
                          type: array
                          description: Kline item as array
                          items:
                            oneOf:
                              - type: string
                              - type: number
                  time:
                    type: integer
